"""Generate reviewable PostgreSQL DDL without reading credentials or connecting.

Usage: python -m database.schema > docs/database-schema.sql
This module intentionally has no apply/migrate command.
"""

from sqlalchemy.dialects.postgresql import dialect
from sqlalchemy.schema import CreateIndex, CreateTable

from database.integrity import POSTGRES_RULES
from database.models import Base


def postgresql_ddl():
    postgres = dialect()
    statements = []
    for table in Base.metadata.sorted_tables:
        statements.append(str(CreateTable(table).compile(dialect=postgres)).strip() + ";")
        for index in sorted(table.indexes, key=lambda item: item.name):
            statements.append(str(CreateIndex(index).compile(dialect=postgres)).strip() + ";")
    statements.extend(sql.strip() + ";" for sql in POSTGRES_RULES)
    output = (
        "-- Next-version shipment schema. Generated by python -m database.schema.\n"
        "-- For an EMPTY staging database, NOT an upgrade of the current app.\n"
        "-- PostgreSQL 16 / Supabase. No storage buckets, login grants or RLS policies are created.\n"
        "BEGIN;\n\n" + "\n\n".join(statements) + "\n\nCOMMIT;\n"
    )
    return "\n".join(line.rstrip() for line in output.splitlines()) + "\n"


if __name__ == "__main__":
    print(postgresql_ddl(), end="")
