-- Next-version shipment schema. Generated by python -m database.schema.
-- For an EMPTY staging database, NOT an upgrade of the current app.
-- PostgreSQL 16 / Supabase. No storage buckets, login grants or RLS policies are created.
BEGIN;

CREATE TABLE admin_users (
	username VARCHAR(120) NOT NULL,
	role VARCHAR(20) DEFAULT 'operator' NOT NULL,
	active BOOLEAN DEFAULT true NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_admin_users PRIMARY KEY (id),
	CONSTRAINT ck_admin_users_username_not_blank CHECK (trim(username) <> ''),
	CONSTRAINT ck_admin_users_valid_role CHECK (role IN ('administrator', 'operator', 'viewer')),
	CONSTRAINT uq_admin_users_username UNIQUE (username)
);

CREATE TABLE companies (
	name VARCHAR(200) NOT NULL,
	registered_address TEXT,
	email VARCHAR(254),
	phone VARCHAR(30),
	active BOOLEAN DEFAULT true NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_companies PRIMARY KEY (id),
	CONSTRAINT ck_companies_name_not_blank CHECK (trim(name) <> ''),
	CONSTRAINT uq_companies_name UNIQUE (name)
);

CREATE TABLE audit_logs (
	actor_id UUID,
	entity_type VARCHAR(100) NOT NULL,
	entity_id UUID NOT NULL,
	action VARCHAR(100) NOT NULL,
	before_values JSONB,
	after_values JSONB,
	recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_audit_logs PRIMARY KEY (id),
	CONSTRAINT ck_audit_logs_description_not_blank CHECK (trim(entity_type) <> '' AND trim(action) <> ''),
	CONSTRAINT fk_audit_logs_actor_id_admin_users FOREIGN KEY(actor_id) REFERENCES admin_users (id) ON DELETE RESTRICT,
	CONSTRAINT ck_audit_logs_before_values_object CHECK (jsonb_typeof(before_values) = 'object'),
	CONSTRAINT ck_audit_logs_after_values_object CHECK (jsonb_typeof(after_values) = 'object')
);

CREATE INDEX ix_audit_logs_actor_id ON audit_logs (actor_id);

CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id, recorded_at);

CREATE TABLE company_locations (
	company_id UUID NOT NULL,
	kind VARCHAR(10) NOT NULL,
	label VARCHAR(100) NOT NULL,
	address TEXT NOT NULL,
	pincode VARCHAR(16),
	is_default BOOLEAN DEFAULT false NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_company_locations PRIMARY KEY (id),
	CONSTRAINT uq_company_locations_company_id_id UNIQUE (company_id, id),
	CONSTRAINT ck_company_locations_valid_kind CHECK (kind IN ('pickup', 'drop')),
	CONSTRAINT ck_company_locations_label_not_blank CHECK (trim(label) <> ''),
	CONSTRAINT ck_company_locations_address_not_blank CHECK (trim(address) <> ''),
	CONSTRAINT fk_company_locations_company_id_companies FOREIGN KEY(company_id) REFERENCES companies (id) ON DELETE RESTRICT
);

CREATE INDEX ix_company_locations_company_id ON company_locations (company_id);

CREATE UNIQUE INDEX uq_company_locations_default ON company_locations (company_id, kind) WHERE is_default;

CREATE TABLE files (
	uploaded_by UUID,
	storage_bucket VARCHAR(255) NOT NULL,
	storage_path VARCHAR(1024) NOT NULL,
	original_filename VARCHAR(255) NOT NULL,
	mime_type VARCHAR(255) NOT NULL,
	size_bytes BIGINT NOT NULL,
	checksum VARCHAR(64),
	uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_files PRIMARY KEY (id),
	CONSTRAINT ck_files_storage_not_blank CHECK (trim(storage_bucket) <> '' AND trim(storage_path) <> ''),
	CONSTRAINT ck_files_metadata_not_blank CHECK (trim(original_filename) <> '' AND trim(mime_type) <> ''),
	CONSTRAINT ck_files_nonnegative_size CHECK (size_bytes >= 0),
	CONSTRAINT ck_files_sha256_length CHECK (length(checksum) = 64),
	CONSTRAINT fk_files_uploaded_by_admin_users FOREIGN KEY(uploaded_by) REFERENCES admin_users (id) ON DELETE RESTRICT,
	CONSTRAINT uq_files_storage_path UNIQUE (storage_path)
);

CREATE INDEX ix_files_uploaded_by ON files (uploaded_by);

CREATE TABLE mis_views (
	created_by UUID,
	name VARCHAR(120) NOT NULL,
	filters JSONB DEFAULT '{}' NOT NULL,
	selected_columns JSONB DEFAULT '[]' NOT NULL,
	preferred_format VARCHAR(10) DEFAULT 'xlsx' NOT NULL,
	notes TEXT,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_mis_views PRIMARY KEY (id),
	CONSTRAINT ck_mis_views_name_not_blank CHECK (trim(name) <> ''),
	CONSTRAINT ck_mis_views_valid_format CHECK (preferred_format IN ('pdf', 'xlsx', 'csv')),
	CONSTRAINT fk_mis_views_created_by_admin_users FOREIGN KEY(created_by) REFERENCES admin_users (id) ON DELETE RESTRICT,
	CONSTRAINT ck_mis_views_filters_object CHECK (jsonb_typeof(filters) = 'object'),
	CONSTRAINT ck_mis_views_selected_columns_array CHECK (jsonb_typeof(selected_columns) = 'array')
);

CREATE INDEX ix_mis_views_created_by ON mis_views (created_by);

CREATE TABLE consignments (
	company_id UUID,
	pickup_location_id UUID,
	drop_location_id UUID,
	identifier_type VARCHAR(12) DEFAULT 'LRN' NOT NULL,
	identifier_value VARCHAR(64) NOT NULL,
	current_status VARCHAR(200) DEFAULT 'Pickup Scheduled' NOT NULL,
	pieces INTEGER DEFAULT '1' NOT NULL,
	chargeable_weight NUMERIC(12, 3),
	chargeable_volume NUMERIC(12, 3),
	pickup_address_snapshot TEXT,
	drop_address_snapshot TEXT,
	planned_pickup_date DATE,
	expected_delivery_date DATE,
	actual_pickup_at TIMESTAMP WITH TIME ZONE,
	actual_delivery_at TIMESTAMP WITH TIME ZONE,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_consignments PRIMARY KEY (id),
	CONSTRAINT fk_consignments_pickup_company FOREIGN KEY(company_id, pickup_location_id) REFERENCES company_locations (company_id, id) ON DELETE RESTRICT,
	CONSTRAINT fk_consignments_drop_company FOREIGN KEY(company_id, drop_location_id) REFERENCES company_locations (company_id, id) ON DELETE RESTRICT,
	CONSTRAINT ck_consignments_preset_requires_company CHECK (company_id IS NOT NULL OR (pickup_location_id IS NULL AND drop_location_id IS NULL)),
	CONSTRAINT ck_consignments_valid_identifier_type CHECK (identifier_type IN ('LRN', 'Order ID', 'AWB')),
	CONSTRAINT ck_consignments_identifier_not_blank CHECK (trim(identifier_value) <> ''),
	CONSTRAINT ck_consignments_status_not_blank CHECK (trim(current_status) <> ''),
	CONSTRAINT ck_consignments_positive_pieces CHECK (pieces >= 1),
	CONSTRAINT ck_consignments_nonnegative_weight CHECK (chargeable_weight >= 0),
	CONSTRAINT ck_consignments_nonnegative_volume CHECK (chargeable_volume >= 0),
	CONSTRAINT ck_consignments_delivery_after_pickup CHECK (actual_delivery_at >= actual_pickup_at),
	CONSTRAINT fk_consignments_company_id_companies FOREIGN KEY(company_id) REFERENCES companies (id) ON DELETE RESTRICT,
	CONSTRAINT fk_consignments_pickup_location_id_company_locations FOREIGN KEY(pickup_location_id) REFERENCES company_locations (id) ON DELETE RESTRICT,
	CONSTRAINT fk_consignments_drop_location_id_company_locations FOREIGN KEY(drop_location_id) REFERENCES company_locations (id) ON DELETE RESTRICT,
	CONSTRAINT uq_consignments_identifier_value UNIQUE (identifier_value)
);

CREATE INDEX ix_consignments_company_id ON consignments (company_id);

CREATE INDEX ix_consignments_current_status_planned_pickup_date ON consignments (current_status, planned_pickup_date);

CREATE INDEX ix_consignments_drop_location_id ON consignments (drop_location_id);

CREATE INDEX ix_consignments_expected_delivery_date ON consignments (expected_delivery_date);

CREATE INDEX ix_consignments_pickup_location_id ON consignments (pickup_location_id);

CREATE INDEX ix_consignments_planned_pickup_date ON consignments (planned_pickup_date);

CREATE TABLE mis_reports (
	view_id UUID,
	generated_by UUID,
	file_id UUID NOT NULL,
	name VARCHAR(120) NOT NULL,
	format VARCHAR(10) NOT NULL,
	filters_snapshot JSONB DEFAULT '{}' NOT NULL,
	columns_snapshot JSONB DEFAULT '[]' NOT NULL,
	metrics_snapshot JSONB DEFAULT '{}' NOT NULL,
	shipment_count INTEGER NOT NULL,
	generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_mis_reports PRIMARY KEY (id),
	CONSTRAINT ck_mis_reports_name_not_blank CHECK (trim(name) <> ''),
	CONSTRAINT ck_mis_reports_valid_format CHECK (format IN ('pdf', 'xlsx', 'csv')),
	CONSTRAINT ck_mis_reports_nonnegative_count CHECK (shipment_count >= 0),
	CONSTRAINT fk_mis_reports_view_id_mis_views FOREIGN KEY(view_id) REFERENCES mis_views (id) ON DELETE SET NULL,
	CONSTRAINT fk_mis_reports_generated_by_admin_users FOREIGN KEY(generated_by) REFERENCES admin_users (id) ON DELETE RESTRICT,
	CONSTRAINT uq_mis_reports_file_id UNIQUE (file_id),
	CONSTRAINT fk_mis_reports_file_id_files FOREIGN KEY(file_id) REFERENCES files (id) ON DELETE RESTRICT,
	CONSTRAINT ck_mis_reports_filters_snapshot_object CHECK (jsonb_typeof(filters_snapshot) = 'object'),
	CONSTRAINT ck_mis_reports_columns_snapshot_array CHECK (jsonb_typeof(columns_snapshot) = 'array'),
	CONSTRAINT ck_mis_reports_metrics_snapshot_object CHECK (jsonb_typeof(metrics_snapshot) = 'object')
);

CREATE INDEX ix_mis_reports_generated_at ON mis_reports (generated_at);

CREATE INDEX ix_mis_reports_generated_by ON mis_reports (generated_by);

CREATE INDEX ix_mis_reports_view_id ON mis_reports (view_id);

CREATE TABLE shipment_documents (
	consignment_id UUID NOT NULL,
	file_id UUID NOT NULL,
	document_type VARCHAR(10) NOT NULL,
	version INTEGER DEFAULT '1' NOT NULL,
	is_current BOOLEAN DEFAULT true NOT NULL,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_shipment_documents PRIMARY KEY (id),
	CONSTRAINT ck_shipment_documents_valid_type CHECK (document_type IN ('POD', 'invoice')),
	CONSTRAINT ck_shipment_documents_positive_version CHECK (version >= 1),
	CONSTRAINT uq_shipment_documents_version UNIQUE (consignment_id, document_type, version),
	CONSTRAINT fk_shipment_documents_consignment_id_consignments FOREIGN KEY(consignment_id) REFERENCES consignments (id) ON DELETE CASCADE,
	CONSTRAINT fk_shipment_documents_file_id_files FOREIGN KEY(file_id) REFERENCES files (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shipment_documents_file_id ON shipment_documents (file_id);

CREATE UNIQUE INDEX uq_shipment_documents_current ON shipment_documents (consignment_id, document_type) WHERE is_current;

CREATE TABLE shipment_events (
	consignment_id UUID NOT NULL,
	recorded_by UUID,
	status VARCHAR(200) NOT NULL,
	occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
	recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	notes TEXT,
	id UUID DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT pk_shipment_events PRIMARY KEY (id),
	CONSTRAINT ck_shipment_events_status_not_blank CHECK (trim(status) <> ''),
	CONSTRAINT fk_shipment_events_consignment_id_consignments FOREIGN KEY(consignment_id) REFERENCES consignments (id) ON DELETE CASCADE,
	CONSTRAINT fk_shipment_events_recorded_by_admin_users FOREIGN KEY(recorded_by) REFERENCES admin_users (id) ON DELETE RESTRICT
);

CREATE INDEX ix_shipment_events_consignment_occurred_at ON shipment_events (consignment_id, occurred_at);

CREATE INDEX ix_shipment_events_recorded_by ON shipment_events (recorded_by);

CREATE OR REPLACE FUNCTION validate_consignment_presets() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE preset_kind text;
    BEGIN
        IF NEW.pickup_location_id IS NOT NULL THEN
            SELECT kind INTO preset_kind FROM company_locations
            WHERE id = NEW.pickup_location_id FOR SHARE;
            IF preset_kind IS DISTINCT FROM 'pickup' THEN
                RAISE EXCEPTION 'Pickup preset must be a pickup location' USING ERRCODE = '23514';
            END IF;
        END IF;
        IF NEW.drop_location_id IS NOT NULL THEN
            SELECT kind INTO preset_kind FROM company_locations
            WHERE id = NEW.drop_location_id FOR SHARE;
            IF preset_kind IS DISTINCT FROM 'drop' THEN
                RAISE EXCEPTION 'Drop preset must be a drop location' USING ERRCODE = '23514';
            END IF;
        END IF;
        RETURN NEW;
    END $$;

CREATE OR REPLACE TRIGGER consignments_validate_presets BEFORE INSERT OR UPDATE
    ON consignments FOR EACH ROW EXECUTE FUNCTION validate_consignment_presets();

CREATE OR REPLACE FUNCTION protect_referenced_location_kind() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF NEW.kind IS DISTINCT FROM OLD.kind AND EXISTS (
            SELECT 1 FROM consignments
            WHERE pickup_location_id = OLD.id OR drop_location_id = OLD.id
        ) THEN
            RAISE EXCEPTION 'Cannot change the kind of a referenced location' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END $$;

CREATE OR REPLACE TRIGGER company_locations_protect_kind BEFORE UPDATE
    ON company_locations FOR EACH ROW EXECUTE FUNCTION protect_referenced_location_kind();

CREATE OR REPLACE FUNCTION protect_mis_report_snapshot() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF ROW(NEW.id, NEW.generated_by, NEW.file_id, NEW.format,
               NEW.filters_snapshot, NEW.columns_snapshot, NEW.metrics_snapshot,
               NEW.shipment_count, NEW.generated_at)
        IS DISTINCT FROM
           ROW(OLD.id, OLD.generated_by, OLD.file_id, OLD.format,
               OLD.filters_snapshot, OLD.columns_snapshot, OLD.metrics_snapshot,
               OLD.shipment_count, OLD.generated_at) THEN
            RAISE EXCEPTION 'Generated report snapshots cannot be edited' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END $$;

CREATE OR REPLACE TRIGGER mis_reports_protect_snapshot BEFORE UPDATE
    ON mis_reports FOR EACH ROW EXECUTE FUNCTION protect_mis_report_snapshot();

COMMIT;
